#!/usr/bin/env bash
# Installing Nginx on Server
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/log/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!"> /var/log/html/index.nginx-debian.html
sudo service nginx restart 
